### ISSUE TITLE
Get board data for frontend

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#15]
`Board` should have a function that returns the current state of the board so I know where to place colours (this is needed when loading a board, too)

**Comment by vincentjguo** [comment]
How do you want the function to return the board state

**Comment by potatoeggy** [comment]
An int array should be fine

**Comment by vincentjguo** [comment]
I think you should update the GUI in parallel with the back-end board, instead of redrawing the entire thing again each time the user places a chip

**Comment by potatoeggy** [comment]
At that point the GUI would have to perform calculations (e.g., where the chip falls), and that would not be ideal. In any case, the method is needed when loading saves.

If `addChip` could return a pair of ints (or int array) showing the last location, that would help too and would leave processing to be purely done by the backend. `checkWin` can be called separately by the GUI.

E: "last location" being where the new chip is located

**Comment by vincentjguo** [comment]
ok I can make the addChip function return a pair ints.  it will be in the form of an array

**Comment by vincentjguo** [comment]
one problem, addChip won't be able to return checkWin, so you would need to call it separately

**Comment by vincentjguo** [comment]
Also, can't the GUI get which button is pressed? As in you already know the position of the array

**Comment by potatoeggy** [comment]
The GUI can get which button is pressed, but will have to calculate where it falls. If the user clicks any empty space in a column with empty space, a square should fall there.

**Comment by vincentjguo** [comment]
ah i see, ok my AI class already has a function for that

**Comment by vincentjguo** [comment]
ok so the board function now returns which row the chip should go in a given column, using that you could update the GUI
