### ISSUE TITLE
AI difficulties

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#16]
I've made 4 options available in the GUI so far, feel free to object:

 - Easy: AI picks randomly
 - Normal: AI depth is not very high (idk, 1-3?)
 - Hard: AI depth is quite high (4+)
 - Impossible: There is no limit to AI depth (the competitive one)

**Comment by vincentjguo** [comment]
yikes the impossible one would be impossible because the AI would actually melt your computer. To see all future moves that would take 8^42 comparisons

**Comment by vincentjguo** [comment]
oh and that's doing it once, my AI does it every turn

**Comment by potatoeggy** [comment]
Oh. Then which one seems to be computationally feasible but is still hard?

**Comment by vincentjguo** [comment]
i need to play around with the depth first. Maybe 7 could be 'impossible'?

**Comment by potatoeggy** [comment]
yeah that seems fine
