### ISSUE TITLE
Improve readability and documentation

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#2]
Within reason, of course.

**Comment by vincentjguo** [comment]
Do we need a header

**Comment by potatoeggy** [comment]
Yup

**Comment by potatoeggy** [comment]
Also meaningful variable names

**Comment by potatoeggy** [comment]
Potentially even javadoc maybe

**Comment by potatoeggy** [comment]
This issue can be closed when there are headers, "meaningful variable names", and at least one comment on every source file in the repository.

**Comment by potatoeggy** [comment]
Complete for frontend.

**Comment by potatoeggy** [comment]
Presumably complete for backend.
