### ISSUE TITLE
Move timer threading issues

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#26]
Multithreading is *probably* the issue. `main` does not seem to run properly on all platforms

**Comment by potatoeggy** [comment]
The branch `move_timer_debug` is used to test fixes.

**Comment by potatoeggy** [comment]
@bob2957 can you run and send the output of the debug branch?

**Comment by vincentjguo** [comment]
`21 21 21` the timer was set to 20 sec

**Comment by potatoeggy** [comment]
Is that the only output?

**Comment by vincentjguo** [comment]
yes

**Comment by potatoeggy** [comment]
Any change in output now?

**Comment by vincentjguo** [comment]
The timer works now...

**Comment by vincentjguo** [comment]
```
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
2b: end loop
2a: maybe checks fail?
loop 11 11
loop 10 11
loop 10 11
loop 9 11
loop 9 11
loop 8 11
loop 8 11
loop 7 11
loop 7 11
loop 6 11
loop 6 11
loop 5 11
loop 5 11
loop 10 11
loop 10 11

Process finished with exit code -1
```

**Comment by vincentjguo** [comment]
here's part of the output

**Comment by potatoeggy** [comment]
That's weird. Does it only work on the debug branch?

**Comment by vincentjguo** [comment]
yep

**Comment by vincentjguo** [comment]
That's strange you added only print statements

**Comment by potatoeggy** [comment]
try again? I'm slowly removing prints

**Comment by vincentjguo** [comment]
Ok so it works without the prints you removed, but once you remove the 2a statement, it breaks again

**Comment by vincentjguo** [comment]
I did some more digging and apparently, without the 2a print statement it won't enter the second while loop

**Comment by potatoeggy** [comment]
but that shouldn't happen

**Comment by vincentjguo** [comment]
Maybe the print statement is affecting one of the while loop conditions?

**Comment by potatoeggy** [comment]
printing shouldn't affect any conditions

**Comment by potatoeggy** [comment]
so we know we enter the first loop no matter what because "exited" was not printed in our first test

i've submitted a workaround, try testing that?

**Comment by vincentjguo** [comment]
yep it works

**Comment by potatoeggy** [comment]
I'm confused now

I have no idea why this is working

**Comment by vincentjguo** [comment]
i know you just added a .sleep

**Comment by vincentjguo** [comment]
it makes no sense

**Comment by potatoeggy** [comment]
alright it's in the main pr

one more test should do it
