### ISSUE TITLE
Alpha-Beta Pruning 

### ISSUE THREAD

**Issue by vincentjguo** [potatoeggy/connectfour#3]
I should probably add this, it makes the AI much faster

**Comment by vincentjguo** [comment]
This would make the AI much faster if I could implement it

**Comment by potatoeggy** [comment]
It's already surprisingly fast, but also surprisingly dumb.

**Comment by vincentjguo** [comment]
wait what for me it takes an eternity.

**Comment by vincentjguo** [comment]
Try running the ai_gui branch, the AI was updated there
