### ISSUE TITLE
Saving and loading

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#30]
The gooey is almost complete. I can complete all mini-backend functions by today. The only remaining TODO is documentation and saving/loading.

**Comment by vincentjguo** [comment]
Can i set this deadline for the final release? It isn't an important feature and it won't take too long to implement

**Comment by vincentjguo** [comment]
Taking a break from the AI for now. What do you want me to save @potatoeggy ?

**Comment by potatoeggy** [comment]
All internal variables in GameWindow

**Comment by vincentjguo** [comment]
Can the user create multiple game saves?

**Comment by potatoeggy** [comment]
No

**Comment by potatoeggy** [comment]
To be accurate, the following needs to be saved (pardon the code-like structure)
```java
					s.writeObject(players);
					s.writeObject(names);
					s.writeInt(gameWindow.getDifficulty());
					s.writeInt(gameWindow.getTurnCount());
					
					// gamewindow
					s.writeObject(gameWindow.getBoard());
					s.writeInt(gameWindow.getCurrentPlayer());
					s.writeInt(gameWindow.getButtonsFilled());

					// mainwindow
					s.writeInt(moveTimerInternal);
					s.writeInt(moveTimerFull);
```

**Comment by vincentjguo** [comment]
I think I have all of them. Review #39
