### ISSUE TITLE
The AI thinks the board is bigger

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#36]
![image](https://user-images.githubusercontent.com/25178974/83664267-c4493c00-a597-11ea-9ce3-71ff57436d36.png)

In Impossible difficulty (other difficulties not tested), when enough coins are stacked so that it reaches the top of the board, the button at the top is spammed, freezing the game until the process is killed. If moving to that impossible spot would give the computer the win, after a longer than normal pause somehow the game thinks that the square there is valid and gives the computer the win, continuing to the end game menu. During the long calculation process, the board rapidly updates, adding and removing coins.

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/83664664-46396500-a598-11ea-843a-5bfc8367c860.png)

**Comment by potatoeggy** [comment]
I can confirm this happens in all difficulties.

EDIT: Actually, this does not happen in Easy (or if it does, it's the the most statistically unlikely thing ever) because Easy is random.

**Comment by potatoeggy** [comment]
This issue can be seen in more detail with the `timer_responsiveness` branch.

**Comment by vincentjguo** [comment]
I did update the AI a bit in `ai_gui`. This might have fixed the problem because I'm trying to recreate it with this branch and I can't.

**Comment by potatoeggy** [comment]
Fixed in 661f221c7042fe30b738282bf45d7855ab7dba75
