### ISSUE TITLE
Need test data for AI

### ISSUE THREAD

**Issue by vincentjguo** [potatoeggy/connectfour#46]
Sometimes the AI makes really bad moves. I need test data in order to debug so @potatoeggy try to beat the AI and reply with a screenshot of the board if you do.

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84160469-36a89900-aa3c-11ea-934b-07d71fdb208d.png)
It let me make three in a row

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84160620-635cb080-aa3c-11ea-95e2-24436d99dddc.png)
my last move: column 3
ai last move: column 4

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84160747-89825080-aa3c-11ea-9dec-3257b18f4a02.png)
my last move: column 5
ai last move: column 6

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84163094-1dedb280-aa3f-11ea-9899-4bf3d01cfd92.png)
Last player move: column 3
Last computer move: column 3

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84163216-3c53ae00-aa3f-11ea-9344-5723a36ee50e.png)
Depth = 5

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84163256-47a6d980-aa3f-11ea-860a-575b02add7c9.png)
Depth = 3

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84163341-673e0200-aa3f-11ea-872e-010f279f6a72.png)
Last player move: column 3
Last computer move: column 2
Depth=4

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84163458-8472d080-aa3f-11ea-8924-f297b2d1df71.png)
Last player move: column 5
Last computer move: column 2
Depth = 4

**Comment by vincentjguo** [comment]
Thanks now I have to hope that I can recreate this on my side

**Comment by potatoeggy** [comment]
Ah, I should send you move history

**Comment by vincentjguo** [comment]
that would help yes

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84168044-f39ef380-aa44-11ea-890c-800f79a3afe1.png)
31452525232

**Comment by vincentjguo** [comment]
Im guessing for most of these the AI is yellow.

**Comment by potatoeggy** [comment]
Yeah. I'll clarify that next time.

**Comment by potatoeggy** [comment]
![image](https://user-images.githubusercontent.com/25178974/84169193-53e26500-aa46-11ea-9bf7-064a672f56d6.png)
4432565545566534343

**Comment by potatoeggy** [comment]
031313121
0313060015121
6655354
3145333634444455535566606
6655443
3136343

**Comment by potatoeggy** [comment]
Test data has been given.
