### ISSUE TITLE
Easy mode breaks when saving and loading

### ISSUE THREAD

**Issue by potatoeggy** [potatoeggy/connectfour#47]
Because we don't save the board state but instead save board *history*, there is a chance that if the AI picks a column that is already full, it will pick another one randomly. This does not occur with other AIs since they always give the same result at a given board state, and they're not stupid enough to pick a full row. As a result, the AI clicks again and messes up everything.

This can be fixed by adding a boolean tag to denote that moves should not be redone, or by adding more processing when deciding a column to place a chip in

**Comment by vincentjguo** [comment]
The AI shouldn't choose a full column. Can you give me a case where this happens?

**Comment by potatoeggy** [comment]
```java
if (difficulty == 0) {
			return (int) (Math.random() * 7); // it's incredibly easy
		}

**Comment by potatoeggy** [comment]
Only happens in easy mode

**Comment by vincentjguo** [comment]
Ah I see. You should add a loop to check if the column is full
