### ISSUE TITLE
Disable computer option to go 2nd

### ISSUE THREAD

**Issue by vincentjguo** [potatoeggy/connectfour#52]
The AI breaks when it goes second. Either we make the first player's move be recorded as `2` in the backend board or we have to disable this option.

**Comment by potatoeggy** [comment]
Why does it break when going second? Is a value hardcoded in the AI? If so, can that be written so that it's not hardcoded?

**Comment by vincentjguo** [comment]
well as I said before, that is going to be really hard to change. The values `1` and `2` are hardcoded in as AI and player respectively.

**Comment by potatoeggy** [comment]
From `master`:
![image](https://user-images.githubusercontent.com/25178974/84181735-5a2d0d00-aa57-11ea-8d45-afa39296e15e.png)

![image](https://user-images.githubusercontent.com/25178974/84181781-6add8300-aa57-11ea-9fcd-b0586eaa1589.png)
55654545

**Comment by potatoeggy** [comment]
Even when going first the AI seems to make some questionable choices

**Comment by vincentjguo** [comment]
Yep, I fixed this issue as of PR #53. Can you test the AI there?

**Comment by potatoeggy** [comment]
It seems stupidity has been largely fixed. However, performance has tanked. It takes about 20 s per move at a depth of 4 after 20 or so pieces.

**Comment by potatoeggy** [comment]
And it takes longer as the game goes on.

**Comment by potatoeggy** [comment]
Is there a way to get the AI to stop calculating and immediately return whatever it has after a time?

**Comment by potatoeggy** [comment]
Depending on the position, it can take 30 s+ even when less than 10 pieces are on the board.

X5X3X1X5X1

**Comment by potatoeggy** [comment]
Fixed in 7766527b514d4b56b9d0409c0697a74d90a240c2.
